"""add persistent agent ledger

Revision ID: 50d8f5c89bed
Revises: 53e64731bb36
Create Date: 2026-08-12 01:16:37.534860

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50d8f5c89bed"
down_revision: str | Sequence[str] | None = "53e64731bb36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("acp_session_id", sa.String(length=200), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column("model", sa.String(length=300), nullable=True),
        sa.Column("thinking_level", sa.String(length=40), nullable=True),
        sa.Column("tool_call_id", sa.String(length=200), nullable=True),
        sa.Column("tool_name", sa.String(length=100), nullable=True),
        sa.Column("input_json", sa.Text(), nullable=True),
        sa.Column("output_json", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["agent_conversations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_ledger_entries_conversation_id"),
        "agent_ledger_entries",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_ledger_entries_run_id"), "agent_ledger_entries", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_ledger_entries_tool_call_id"),
        "agent_ledger_entries",
        ["tool_call_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_ledger_entries_tool_call_id"), table_name="agent_ledger_entries")
    op.drop_index(op.f("ix_agent_ledger_entries_run_id"), table_name="agent_ledger_entries")
    op.drop_index(
        op.f("ix_agent_ledger_entries_conversation_id"), table_name="agent_ledger_entries"
    )
    op.drop_table("agent_ledger_entries")
    # ### end Alembic commands ###
